### ISSUE TITLE
Make error pages opt-in

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers-errors#24]
As seen in https://github.com/feathersjs/feathers-mongoose/issues/56 it is very easy to make a request and get an error page which looks like a mistake. Services on the other hand always return JSON. I'm wondering if we should make the HTML error pages opt-in (passing the filename in the options) and add them to the generator instead.

**Comment by marshallswain** [comment]
I would definitely appreciate this.

**Comment by ekryski** [comment]
It may sound stupid but I think it’s actually sort of important to support this by default because it gives people a sense of security and makes Feathers look polished. Like, ​_”man these guys have thought of everything. Even minimal error pages”_​.

If you don't want to use the middleware you can easily just write your own or use a different express error handler.

That being said I think we should do 3 things:

- you should be able to turn off HTML with something like `html:false`
- we should also check to see if the request was XHR and it doesn't accept JSON assume the user forgot to set the `Accepts` header.
- We should provide a `default.html` page that show a "General Error" for any non 404 or 500 errors.

**Comment by marshallswain** [comment]
That sounds reasonable.

**Comment by daffl** [comment]
Opting in has been added in #25
