### ISSUE TITLE
[Proposal] use verror

### ISSUE THREAD

**Issue by bertho-zero** [feathersjs/feathers-errors#88]
Do you think using [verror](https://github.com/joyent/node-verror) with feathers-errors?

**Comment by daffl** [comment]
The error module is a little finicky because it has to work reliably on the client and the server so it shouldn't have any external dependencies.

It looks like verror is pulling in several libraries (`extsprintf`, `core-util-is`, `util`, `assert-plus`) which will probably add to the - currently pretty slim - client side build.

**Comment by daffl** [comment]
Thanks for the suggestion again @bertho-zero. I'm going to close this one since it looks like we'd be pulling in a whole bunch of additional dependencies (which is fine on Node but on the client we do want to keep the builds as small as possible).

Maybe we can eventually make `feathers-errors` more generic (it's not really Feathers specific already).
